config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  get 'tags/:tag', to: 'ideas#index' , as: :tag
  get 'pages/info'

  resources :ideas
  root to: 'ideas#index'
  get "pages/info"

  namespace :account do
    resources :ideas
  end

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	mount_uploader :picture, PictureUploader
	acts_as_taggable
	belongs_to :author, class_name: "User", foreign_key: :user_id
	def editable_by?(user)
		user && user == author
	end
end

app/models/settings.rb
class Settings < Settingslogic
  source "#{Rails.root}/config/application.yml"
  namespace Rails.env
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates_presence_of :password, unless: :through_third_website
  has_secure_password validations: false
  
  extend OmniauthCallbacks

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  has_many :ideas

  private

  def through_third_website
    self.provider.present?
  end
end

app/controllers/account/ideas_controller.rb
class Account::IdeasController < ApplicationController
	before_action :authenticate_user!

	 def index
	   @ideas = current_user.ideas.order("updated_at DESC")
	 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy] 
  # GET /ideas
  # GET /ideas.json
  def index
    if params[:tag]
      @ideas = Idea.tagged_with(params[:tag])
    else
      @ideas = Idea.all     
    end
    
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)
    @idea.author = current_user
    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = current_user.ideas.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:title, :description, :picture , :tag_list)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/helpers/account/ideas_helper.rb
module Account::IdeasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ideas/_form.html.erb
<%= form_for(@idea) do |f| %>
  <% if @idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% @idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tag_list, "Tags (separated by commas) " %><br>
    <%= f.text_field :tag_list %>
  <%# tag_cloud Idea.tag_counts, %w[tag_btn] do |tag, css_class| %>
    <!-- <div class="tag_btn"><%#=  tag.name %></div> -->
  <%# end %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>




<div id="pins" class="transitions-enabled">
      <% @ideas.each do |idea| %>
     <div class="box panel panel-default">
       <%= image_tag idea.picture_url() if idea.picture? %>
        <h2> <%= link_to idea.title, idea %></h2>
        <div class="desc">
          <%= idea.description %>
        </div>
        <p class="user">

          <img src="http://graph.facebook.com/<%= idea.author.fb_id %>/picture?type=square" alt="">
          <%= raw idea.tag_list.map {|t| link_to t, tag_path(t)}.join(',') %>
          <% if idea.editable_by?(current_user) %>
          <%= link_to 'Edit', edit_idea_path(idea) %>
          <% end %>
        </p>
     </div>
      <% end %>
</div>

app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form' %>

<%= link_to 'Back', ideas_path %>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @idea.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>
<p>
  <%= image_tag(@idea.picture_url, width: 600) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pama</title>
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
	<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">帕瑪設計牆</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><%= link_to '新增', new_idea_path %></li>
      </ul>
      <p class="navbar-text pull-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to "我的文章", account_ideas_path,:class => 'navbar-link' %>
          <%= link_to '編輯檔案', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "登出", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "註冊", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "登入", new_user_session_path, :class => 'navbar-link'  %>
          <%= link_to("Facebook Login", Settings.domain + user_omniauth_authorize_path(:facebook)) %>
        <% end %>
        </p>
    </div>
  </div>
</nav>
<div id="tag_cloud">
  <% tag_cloud Idea.tag_counts, %w[tag_link] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>
<div class="container">
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <%= yield %>
</div>
<footer>
  <div class="container">
    Pama Salon 2016
  </div>
</footer>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/info.html.erb
<h1>Pages#info</h1>
<p>Find me in app/views/pages/info.html.erb</p>